name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Make gradlew executable (important)
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Build APK with Gradle
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    # Step 5: Upload APK as artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ChessCoachApp
        path: app/build/outputs/apk/debug/app-debug.apk
